# Postgres connection (edit when deploying)
[postgres]
host = "16.170.143.253"
port = 5432
database = "miva_ai_db"
user = "admin"
password = "password123"  # <-- replace; do NOT commit real creds
sslmode = "prefer"        # "require" if your server enforces SSL
schema = "public"
